version: '2.2'

services:
  db:
    image: mysql:8.0.25
    container_name: database
    ports:
        - "3306:3306"
    volumes:
        - /var/lib/mysql
        - $PWD/db_scripts:/docker-entrypoint-initdb.d
    environment:
        - MYSQL_USER=myuser
        - MYSQL_PASSWORD=mypass
        - MYSQL_DATABASE=test_db
        - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  
  
  notebook:
    image: jupyter/scipy-notebook:latest
    container_name: notebook
    volumes:
      - $PWD/notebooks:/home/jovyan/
    ports:
      - "8888:8888"


